# Generated by Django 5.0.6 on 2024-05-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_diagnosis',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pwz_pwzf',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ref_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AlterField(
            model_name='recordings',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='FaceMotionMonitorApp.userprofile'),
        ),
        migrations.DeleteModel(
            name='DoctorAndPatient',
        ),
    ]
