# Generated by Django 5.0.4 on 2024-05-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0002_remove_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pwz_pwzf', models.CharField(max_length=10, unique=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FaceMotionMonitorApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('date_of_diagnosis', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('ref_photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FaceMotionMonitorApp.refphotos')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FaceMotionMonitorApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAndPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_relations', to='FaceMotionMonitorApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_relations', to='FaceMotionMonitorApp.patient')),
            ],
        ),
    ]
