# Generated by Django 5.0.6 on 2024-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0004_remove_patient_ref_photo_refphotos_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorandpatient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorandpatient',
            name='patient',
        ),
        migrations.AddField(
            model_name='doctorandpatient',
            name='doctor',
            field=models.ManyToManyField(related_name='patient_relations', to='FaceMotionMonitorApp.doctor'),
        ),
        migrations.AddField(
            model_name='doctorandpatient',
            name='patient',
            field=models.ManyToManyField(related_name='doctor_relations', to='FaceMotionMonitorApp.patient'),
        ),
    ]
