# Generated by Django 5.0.6 on 2024-05-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0007_alter_doctorandpatient_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorandpatient',
            name='doctor_id',
            field=models.IntegerField(default=1),
        ),
    ]
