# Generated by Django 5.0.6 on 2024-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0008_alter_doctorandpatient_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorandpatient',
            name='patient_id',
            field=models.IntegerField(default=1),
        ),
    ]
