# Generated by Django 5.0.6 on 2024-05-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0009_alter_doctorandpatient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='login',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
