# Generated by Django 5.0.4 on 2024-05-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0010_alter_auth_login_alter_auth_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framelandmarks',
            old_name='x_cord',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='refphotolandmarks',
            old_name='x_cord',
            new_name='distance',
        ),
        migrations.RemoveField(
            model_name='framelandmarks',
            name='y_cord',
        ),
        migrations.RemoveField(
            model_name='refphotolandmarks',
            name='y_cord',
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('difference_mouth', models.FloatField()),
                ('difference_2', models.FloatField()),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='FaceMotionMonitorApp.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Smile',
        ),
    ]
