# Generated by Django 5.0.6 on 2024-06-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0011_rename_x_cord_framelandmarks_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_diagnosis',
            field=models.DateField(null=True),
        ),
    ]
