# Generated by Django 5.0.6 on 2024-06-22 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0012_alter_patient_date_of_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refphotolandmarks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='refphotolandmarks',
            name='ref_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceMotionMonitorApp.refphotos'),
        ),
        migrations.AlterUniqueTogether(
            name='refphotolandmarks',
            unique_together={('ref_photo', 'landmark_number')},
        ),
    ]
