# Generated by Django 5.0.6 on 2024-06-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0013_alter_refphotolandmarks_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framelandmarks',
            name='frame_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceMotionMonitorApp.frames'),
        ),
        migrations.AlterField(
            model_name='frames',
            name='recording_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceMotionMonitorApp.recordings'),
        ),
        migrations.AlterField(
            model_name='recordings',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FaceMotionMonitorApp.userprofile'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FaceMotionMonitorApp.userprofile'),
        ),
    ]
