# Generated by Django 5.0.6 on 2024-06-22 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0014_alter_framelandmarks_frame_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FaceMotionMonitorApp.patient'),
        ),
    ]
