# Generated by Django 5.0.4 on 2024-06-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMotionMonitorApp', '0015_alter_reports_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceMotionMonitorApp.patient'),
        ),
    ]
